[tool.commitizen]
name = "cz_conventional_commits"
version = "v0.0.1"
tag_format = "$version"
version_files = [
    "pop-transition/__version__.py"
]
bump_message = "release $current_version → $new_version"